----
all:
  vars:
    ansible_user: ubuntu 
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
kube_masters:
  hosts:
    master1:
      ansible_host: 10.31.101.167
kube_workers:
  hosts:
    worker1:
      ansible_host: 10.31.102.76
    worker2:
      ansible_host: 10.31.102.251
